name: bidzna
services:
  ollama:
    image: "ollama/ollama:latest"
    ports:
      - "11434:11434"
    volumes:
      - ollama_storage:/root/.ollama
  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "8080:8080"
    environment:
      - WEBUI_AUTH=False
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
  qdrant:
    image: "qdrant/qdrant:latest"
    ports:
      - "6334"
volumes:
  ollama_storage:
  open-webui:
